recipes:
  - name: "logs"
    description: "Stream logs from a Docker container"
    category: "docker"
    help: |
      This recipe streams logs from a Docker container.

      The recipe will:
        1. List all running Docker containers
        2. Prompt you to select a container
        3. Stream logs from the selected container
        4. Display a message when log streaming ends

      Requirements:
        - Docker must be installed and running
        - You must have permissions to access Docker

      Special features:
        - Uses the stream execution mode to display logs in real-time
        - Automatically retrieves container names from docker ps
        - Press Ctrl+C to stop log streaming
    vars:
      "filter": ""
      "filter_exclude": "2>&1"
      "filter_base": "| grep -i --color=always"
      "filter_lines": 5
    operations:
      - name: "Docker Container Select"
        uses: "docker_container_select"
        silent: true

      - name: "Filter Lines"
        id: "filter_lines"
        command: echo {{ .lines }}
        condition: .lines != "false"
        silent: true

      - name: "Filter"
        id: "filter_base"
        command: echo "{{ .filter_exclude }} {{ .filter_base }} -A {{ .filter_lines }} -B {{ .filter_lines }}"
        condition: .f == "true"
        silent: true

      - name: "Highlight"
        id: "filter"
        command: echo "{{ .filter_base }} '{{ .input }}'"
        condition: .input != "false"
        silent: true

      - name: "Stream Logs"
        command: docker logs --follow {{ .docker_selected_container }} {{ .filter }}
        execution_mode: "stream"
