recipes:
  - name: "logs"
    description: "Stream logs from a Docker container with advanced filtering"
    category: "docker"
    help: |
      Streams logs from a selected Docker container with filtering options.

      Usage:
        shef docker logs [TEXT]                 # Stream logs with optional text highlighting
        shef docker logs -f [TEXT]              # Filter to only show matching entries
        shef docker logs --lines=N              # Set context lines (default: 5)
        shef docker logs --since=TIME           # Show logs since time (e.g., "1h", "72h", "2025-01-01")

      Press Ctrl+C to stop log streaming.
    vars:
      "filter_string": ""
      "filter_base": "2>&1 | grep --color=always -i"
      "filter_lines": 5
      "since": ""
    operations:
      - uses: "docker.container.select"
        id: "container"
        silent: true

      - name: "Since"
        id: "since"
        command: echo '--since="{{ .since }}"'
        condition: .since != "false"
        silent: true

      - name: "Filter Lines"
        id: "filter_lines"
        command: echo {{ .lines }}
        condition: .lines != "false"
        silent: true

      - name: "Filter"
        id: "filter_string"
        command: echo '{{ .filter_base }} -B{{ .filter_lines }} -A{{ .filter_lines }} "{{ .input }}"'
        condition: .f == "true" && .input != "false"
        silent: true

      - name: "Highlight"
        id: "filter_string"
        command: echo '{{ .filter_base }} -E "{{ .input }}|$"'
        condition: .f != "true" && .input != "false"
        silent: true

      - name: "Stream Logs"
        command: docker logs --follow {{ .since }} {{ .container }} {{ .filter_string }}
        execution_mode: "stream"
