recipes:
  - name: "logs"
    description: "Stream logs from a Docker container with advanced filtering"
    category: "docker"
    help: |
      This recipe streams logs from a Docker container.

      The recipe will:
        1. List all running Docker containers
        2. Prompt you to select a container
        3. Stream logs from the selected container

      Requirements:
        - Docker must be installed and running
        - You must have permissions to access Docker

      Options:
        -f              Filter and highlight log entries
        --lines=NUMBER  Number of context lines before and after matches (default: 5)
        --since=STRING  Show logs from the specified time forward
                        Examples: "1h" (last hour), "72h" (last 3 days), "2025-01-01" (since date)

      Positional Arguments:
        STRING  Text to search for in logs (uses first argument)

      Examples:
        shef docker logs                        # Stream all logs from a selected container
        shef docker logs 'error'                # Stream logs highlighting "error" entries
        shef docker logs -f 'error'             # Filter and highlight "error" entries
        shef docker logs -f 'error' --lines=10  # Filter with 10 lines of context
        shef docker logs --since=3h             # Stream all logs from the last 3 hours

      Features:
        - Uses the stream execution mode to display logs in real-time
        - Automatically retrieves container names from docker ps
        - Press Ctrl+C to stop log streaming
    vars:
      "filter": ""
      "filter_base": "2>&1 | grep --color=always -i"
      "filter_lines": 5
      "since": ""
    operations:
      - uses: "docker_container_select"
        id: "container"
        silent: true

      - name: "Since"
        id: "since"
        command: echo '--since="{{ .since }}"'
        condition: .since != "false"
        silent: true

      - name: "Filter Lines"
        id: "filter_lines"
        command: echo {{ .lines }}
        condition: .lines != "false"
        silent: true

      - name: "Filter"
        id: "filter"
        command: echo '{{ .filter_base }} -B{{ .filter_lines }} -A{{ .filter_lines }} "{{ .input }}"'
        condition: .f == "true" && .input != "false"
        silent: true

      - name: "Highlight"
        id: "filter"
        command: echo '{{ .filter_base }} -E "{{ .input }}|$"'
        condition: .f != "true" && .input != "false"
        silent: true

      - name: "Stream Logs"
        command: docker logs --follow {{ .since }} {{ .container }} {{ .filter }}
        execution_mode: "stream"
