recipes:
  - name: "shell"
    description: "Shell into a Docker container"
    category: "docker"
    help: |
      This recipe opens an interactive shell into a Docker container.

      The recipe will:
        1. List all running Docker containers
        2. Prompt you to select a container
        3. Open an interactive shell session in the selected container
        4. Display a message when the shell session ends

      Requirements:
        - Docker must be installed and running
        - You must have permissions to access Docker
        - The container must have bash installed

      Special features:
        - Uses the interactive execution mode for shell access
        - Automatically retrieves container names from docker ps
        - Exit the shell (usually with 'exit' command)
    operations:
      - name: "List Containers"
        id: "list_containers"
        command: docker ps --format "{{ `{{ .Names }}` }}"
        silent: true

      - name: "Select Container"
        id: "select_container"
        command: echo "Shelling into {{ .container }}..."
        prompts:
          - name: "Container Select"
            id: "container"
            type: "select"
            message: "Select a container"
            source_operation: "list_containers"

      - name: "Execute Shell"
        command: docker exec -it {{ .container }} bash
        execution_mode: "interactive"

      - name: "Show Message After Shell Exit"
        command: echo {{ color "green" "Shell session closed. Welcome back!" }}
