recipes:
  - name: "shell"
    description: "Shell into a Docker container"
    category: "docker"
    operations:
      - name: "List Containers"
        id: "list_containers"
        command: docker ps --format "{{ `{{ .Names }}` }}"
        silent: true

      - name: "Select Container"
        id: "select_container"
        command: echo "Shelling into {{ .container }}..."
        prompts:
          - name: "Container Select"
            id: "container"
            type: "select"
            message: "Select a container"
            source_operation: "list_containers"

      - name: "Execute Shell"
        command: docker exec -it {{ .container }} bash
        execution_mode: "interactive"

      - name: "Show Message After Shell Exit"
        command: echo {{ color "green" "Shell session closed. Welcome back!" }}
