recipes:
  - name: "shell"
    description: "Shell into a Docker container"
    category: "docker"
    help: |
      This recipe opens an interactive shell into a Docker container.

      The recipe will:
        1. List all running Docker containers
        2. Prompt you to select a container
        3. Open an interactive shell session in the selected container
        4. Display a message when the shell session ends

      Requirements:
        - Docker must be installed and running
        - You must have permissions to access Docker
        - The container must have bash installed

      Special features:
        - Uses the interactive execution mode for shell access
        - Automatically retrieves container names from docker ps
        - Exit the shell (usually with 'exit' command)
    operations:
      - name: "Docker Container Select"
        uses: "docker_container_select"
        silent: true

      - name: "Docker Container Shell"
        uses: "docker_container_shell"
        silent: true

      - name: "Execute Shell"
        command: docker exec -it {{ .docker_selected_container }} {{ .docker_shell }}
        execution_mode: "interactive"
