recipes:
  - name: "shell"
    description: "Shell into a Docker container"
    category: "docker"
    help: |
      Opens an interactive shell session into a running Docker container.

      Usage:
        shef docker shell                   # Select container and open interactive shell

      Exit the shell session with the 'exit' command.
    operations:
      - uses: "docker.container.select"
        id: "docker_container"
        silent: true

      - uses: "docker.which.shell"
        id: "docker_shell"
        with:
          container: "{{ .docker_container }}"
        silent: true

      - name: "Execute Shell"
        command: docker exec -it {{ .docker_container }} {{ .docker_shell }}
        execution_mode: "interactive"
