recipes:
  - name: "build"
    description: "Build the shef Go project"
    category: "tools"
    operations:
      - name: "Check Go Environment"
        id: "check_go"
        command: "go version"
        transform: "{{ .input | trim }}"

      - name: "Confirm Build"
        id: "confirm_op"
        command: "echo 'Preparing to build shef...'"
        prompts:
          - name: "confirm_build"
            type: "confirm"
            message: "Ready to build the shef project. Continue?"
            default: "true"

      - name: "Build Project"
        id: "build_op"
        command: "go build -o shef main.go"
        condition: "confirm_build == true"
        on_success: "show_success"
        on_failure: "show_failure"

      - name: "Show Success"
        id: "show_success"
        command: "ls -lah shef && echo 'Build successful!'"

      - name: "Show Failure"
        id: "show_failure"
        command: "echo 'Build failed or was cancelled.'"
        condition: "build_op.failure || confirm_build != true"
