recipes:
  - name: "project"
    description: "Select a GCP project"
    category: "gcp"
    help: |
      Selects or displays the current Google Cloud Platform project.

      Usage:
        shef gcp project                    # Select a GCP project
        shef gcp project -w                 # Show current project without changing
    operations:
      - name: "GCP Project Select"
        id: "project"
        uses: "gcp.project.select"
        condition: .w != "true" && .which != "true"
        silent: true
        on_success: "exit"

      - name: "GCP Current Project"
        id: "project"
        uses: "gcp.project.current"
        condition: .w == "true" || .which == "true"
        silent: true
        on_success: "exit"

      - name: "Show Selected Project"
        id: "exit"
        command: echo "Selected project:" {{ style "bold" (color "green" .project) }}
        exit: true
