recipes:
  - name: "project"
    description: "Select a GCP project"
    category: "gcp"
    operations:
      - name: "List Projects"
        id: "list_projects"
        command: gcloud projects list --filter="NOT project_id:sys-*" --format="value(name,project_id)" | awk '{print $1 " (" $2 ")|" $2}'
        silent: true

      - name: "Format Display Options"
        id: "display_options"
        command: cut -d'|' -f1 <<< "{{ .list_projects }}"
        silent: true

      - name: "Select Project"
        id: "selected_display"
        command: echo "{{ .project_display }}"
        silent: true
        prompts:
          - name: "project_display"
            type: "select"
            message: "Select a project"
            source_operation: "display_options"

      - name: "Extract Project ID"
        id: "project_id"
        command: |
          selected="{{ .selected_display }}"
          while IFS= read -r line; do
            display=$(echo "$line" | cut -d'|' -f1)
            id=$(echo "$line" | cut -d'|' -f2)
            if [ "$display" = "$selected" ]; then
              echo "$id"
              break
            fi
          done <<< "{{ .list_projects }}"
        silent: true

      - name: "Set Project"
        command: gcloud config set project {{ .project_id }}
        silent: true

      - name: "Get Selected Project"
        id: "selected_project"
        command: gcloud config get-value project
        silent: true

      - name: "Show Selected Project"
        command: echo "Selected project:" {{ style "bold" (color "green" .selected_project) }}
