components:
  - id: "gcp.project.current"
    operations:
      - command: gcloud config get-value project

  - id: "gcp.project.select"
    operations:
      - uses: "gcp.project.current"
        id: "current_project"
        silent: true

      - id: "projects_list"
        command: gcloud projects list --filter="NOT project_id:sys-*" --format="value(project_id,name)" | awk '{print $1 "=" $2}'
        silent: true

      - id: "selected_project"
        command: echo "{{ .gcp_project_prompt }}"
        silent: true
        prompts:
          - id: "gcp_project_prompt"
            type: "select"
            message: "Select a GCP project"
            source_operation: "projects_list"
            default: "{{ .current_project }}"

      - command: gcloud config set project {{ .selected_project }}
        silent: true

      - command: echo "{{ .selected_project }}"
