components:
  # Database Operations
  # Command: sqlite3 db.sqlite ".tables"                           # List SQLite tables
  # Command: sqlite3 db.sqlite "SELECT * FROM table"               # Simple SQLite query
  # Command: sqlite3 db.sqlite ".schema table"                     # Show table schema
  # Command: sqlite3 db.sqlite ".headers on" "SELECT * FROM table" # Include headers
  # Command: sqlite3 db.sqlite -csv "SELECT * FROM table"          # Output as CSV
  # Command: sqlite3 db.sqlite "CREATE TABLE t(id,name)"           # Create table
  # Command: sqlite3 db.sqlite "INSERT INTO t VALUES(1,'name')"    # Insert data
  # Command: sqlite3 db.sqlite ".dump"                             # Dump database
  # Command: sqlite3 db.sqlite < dump.sql                          # Import SQL
  # Command: sqlite3 db.sqlite ".mode csv" ".import file.csv t"    # Import CSV
  # Command: sqlite3 db.sqlite ".backup backup.db"                 # Backup database
  # Command: echo "select version();" | psql -t dbname             # PostgreSQL version
  # Command: echo "\dt" | psql -t dbname                           # PostgreSQL list tables
  # Command: echo "select * from table;" | psql -t dbname          # PostgreSQL query
  # Command: echo "select column from table;" | psql -t dbname -A  # PostgreSQL query without formatting
  # Command: echo "SHOW TABLES;" | mysql -u user -p dbname         # MySQL list tables
  # Command: echo "SELECT * FROM table;" | mysql -u user -p dbname # MySQL query
  # Command: echo "DESCRIBE table;" | mysql -u user -p dbname      # MySQL table structure
  # Command: echo "SHOW CREATE TABLE table;" | mysql -u user -p dbname # MySQL create table statement
  # Command: mongodb-compass-community --uri="mongodb://localhost:27017" # MongoDB GUI client
  # Command: mongodump --db=dbname --out=backup                    # MongoDB database dump
  # Command: mongorestore --db=dbname backup/dbname                # MongoDB database restore
  # Command: redis-cli info                                        # Redis server info
  # Command: redis-cli get key                                     # Redis get value
  # Command: redis-cli set key value                               # Redis set value
  # Command: redis-cli keys *                                      # Redis list keys