components:
  # Logging and Monitoring
  # Command: dmesg                                                 # Display kernel messages
  # Command: dmesg -T                                              # Display with human-readable timestamps
  # Command: dmesg | grep -i error                                 # Find kernel errors
  # Command: dmesg -w                                              # Watch for new kernel messages
  # Command: dmesg -c                                              # Clear kernel ring buffer
  # Command: journalctl                                            # Query systemd journal
  # Command: journalctl -b                                         # Show logs since boot
  # Command: journalctl -u service                                 # Show logs for specific service
  # Command: journalctl -f                                         # Follow new log entries
  # Command: journalctl --since today                              # Show logs from today
  # Command: journalctl --since "2023-01-01 00:00:00"              # Show logs since date
  # Command: journalctl -p err                                     # Show error and above
  # Command: tail -f /var/log/syslog                               # Follow system log
  # Command: tail -f /var/log/auth.log                             # Follow authentication log
  # Command: less +F /var/log/messages                             # View and follow system messages
  # Command: zcat /var/log/syslog.1.gz                             # View compressed log
  # Command: grep "error" /var/log/syslog                          # Find errors in log
  # Command: awk '/ERROR/ {print $0}' /var/log/syslog              # Find ERROR entries
  # Command: logrotate -f /etc/logrotate.conf                      # Force log rotation
  # Command: logger "Message to syslog"                            # Write to syslog
  # Command: rsyslogd -N1                                          # Check rsyslog config syntax
  # Command: ausearch -ts today -i                                 # Search audit logs from today
  # Command: ausearch -f /etc/passwd -i                            # Find file access events
  # Command: aureport -au                                          # Authentication report from audit logs
  # Command: aureport --summary                                    # Summary report
  # Command: lastlog                                               # Show last login for all users