components:
  - id: "docker_container_list"
    name: "Docker Container List"
    description: "Gets all Docker containers and filter results, if desired"
    inputs:
      - name: "Container List Filter"
        id: "list_filter"
        description: "Filter the container results. Must be a string list: '[container-1 container-2 container-3]'"
    operations:
      - name: "List Docker Containers"
        id: "docker_list_containers"
        command: docker ps --format "{{ `{{ .Names }}` }}"
        silent: true

      - name: "Filter Containers"
        id: "docker_list_containers"
        transform: '{{ overlap .docker_list_containers .list_filter }}'
        condition: .list_filter != "[]"
        silent: true

  - id: "docker_container_select"
    name: "Docker Container Select"
    description: "Gets all Docker containers and prompts the user to select one"
    inputs:
      - name: "Container Select Filter"
        id: "select_filter"
        description: "Filter the select container list"
    operations:
      - name: "Docker Container Select"
        uses: "docker_container_list"
        silent: true
        with:
          list_filter: "{{ .select_filter }}"

      - name: "Select Docker Container"
        id: "docker_selected_container"
        command: echo "{{ .docker_container }}"
        silent: true
        prompts:
          - name: "Container Select"
            id: "docker_container"
            type: "select"
            message: "Select a container"
            source_operation: "docker_list_containers"

  - id: "docker_container_multiselect"
    name: "Docker Container Multi-Select"
    description: "Gets all Docker containers and prompts the user to select one or more containers"
    inputs:
      - name: "Container Multi-Select Filter"
        id: "multiselect_filter"
        description: "Filter the multi-select container list"
    operations:
      - name: "Docker Container Multi-Select"
        uses: "docker_container_list"
        with:
          list_filter: "{{ .multiselect_filter }}"
        silent: true

      - name: "Multi-Select Docker Container"
        id: "docker_multiselect_containers"
        command: echo {{ .docker_multiselect_containers }}
        silent: true
        prompts:
          - name: "Container Select"
            id: "docker_multiselect_containers"
            type: "multiselect"
            message: "Select one or more containers"
            source_operation: "docker_list_containers"

  - id: "docker_container_shell"
    name: "Docker Container Shell"
    description: "Determines what shell a container uses"
    operations:
      - name: "Get Shell"
        id: "docker_shell"
        command: |
          if docker exec {{ .docker_selected_container }} which bash >/dev/null 2>&1; then
            echo "bash"
          elif docker exec {{ .docker_selected_container }} which zsh >/dev/null 2>&1; then
            echo "zsh"
          elif docker exec {{ .docker_selected_container }} which dash >/dev/null 2>&1; then
            echo "dash"
          elif docker exec {{ .docker_selected_container }} which ksh >/dev/null 2>&1; then
            echo "ksh"
          elif docker exec {{ .docker_selected_container }} which tcsh >/dev/null 2>&1; then
            echo "tcsh"
          elif docker exec {{ .docker_selected_container }} which fish >/dev/null 2>&1; then
            echo "fish"
          elif docker exec {{ .docker_selected_container }} which ash >/dev/null 2>&1; then
            echo "ash"
          elif docker exec {{ .docker_selected_container }} which sh >/dev/null 2>&1; then
            echo "sh"
          else
            exit 1
          fi
        on_failure: "handle_shell_error"

      - name: "Error"
        id: "handle_shell_error"
        command: echo {{ color "red" "No common shell found in container." }}
        exit: true
