components:
  - id: "docker_container_select"
    name: "Docker Container Select"
    description: "Gets all Docker containers and prompts the user to select one"
    operations:
      - name: "List Docker Containers"
        id: "docker_list_containers"
        command: docker ps --format "{{ `{{ .Names }}` }}"
        silent: true

      - name: "Select Docker Container"
        id: "docker_selected_container"
        command: echo "{{ .docker_container }}"
        prompts:
          - name: "Container Select"
            id: "docker_container"
            type: "select"
            message: "Select a container"
            source_operation: "docker_list_containers"

  - id: "docker_container_shell"
    name: "Docker Container Shell"
    description: "Determines what shell a container uses"
    operations:
      - name: "Get Shell"
        id: "docker_shell"
        command: |
          if docker exec {{ .docker_selected_container }} which bash >/dev/null 2>&1; then
            echo "bash"
          elif docker exec {{ .docker_selected_container }} which zsh >/dev/null 2>&1; then
            echo "zsh"
          elif docker exec {{ .docker_selected_container }} which dash >/dev/null 2>&1; then
            echo "dash"
          elif docker exec {{ .docker_selected_container }} which ksh >/dev/null 2>&1; then
            echo "ksh"
          elif docker exec {{ .docker_selected_container }} which tcsh >/dev/null 2>&1; then
            echo "tcsh"
          elif docker exec {{ .docker_selected_container }} which fish >/dev/null 2>&1; then
            echo "fish"
          elif docker exec {{ .docker_selected_container }} which ash >/dev/null 2>&1; then
            echo "ash"
          elif docker exec {{ .docker_selected_container }} which sh >/dev/null 2>&1; then
            echo "sh"
          else
            exit 1
          fi
        on_failure: "handle_shell_error"

      - name: "Error"
        id: "handle_shell_error"
        command: echo {{ color "red" "No common shell found in container." }}
        exit: true
